apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeview.fullname" . }}
  labels:
{{ include "kubeview.labels" . | indent 4 }}
data:
  env.js: |-
    (function() {
      window.INCLUDE_NAMESPACES = {{ .Values.namespaces.show | toJson }}
      window.REMOVE_NAMESPACES = {{ .Values.namespaces.hide | toJson }}
    }());
